//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        public int projeID { get; set; }
        public string projeBaslik { get; set; }
        public string projeLink { get; set; }
        public string projeResim { get; set; }
    }
}
