//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Yorum
    {
        public int yorumID { get; set; }

        [Required(ErrorMessage ="Ad Soyad boþ geçilemez!")]
        [StringLength(100, ErrorMessage = "Ad Soyad en az 3 karakter olmalýdýr!", MinimumLength = 3)]
        public string adSoyad { get; set; }

        [Required(ErrorMessage = "Yorum boþ geçilemez!")]
        [StringLength(500, ErrorMessage = "Yorumunuz 2-500 karakter aralýðýnda olmalýdýr!", MinimumLength = 2)]
        public string icerik { get; set; }

        public Nullable<int> makaleID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
